[project]
name = "WIMP"
version = "0.2.0"

git_repo_url = "https://github.com/BillyTheSquid21/wimp/"
git_default_branch = "master"

[paths]
compile_commands = "build/compile_commands.json"

[pages]
paths = [
    "README.md"
]

[ignore]
paths = [
    "/dependencies/",
    "/tests/",
    "/wimp/src/utility/",
    "/wimp/src/wimp_data.c",
    "/wimp/src/wimp_instruction.c",
    "/wimp/src/wimp_log.c",
    "/wimp/src/wimp_process_table.c",
    "/wimp/src/wimp_process.c",
    "/wimp/src/wimp_reciever.c",
    "/wimp/src/wimp_server.c",
]
