name: Run Tests

on:
    push:
        branches: [ main, develop, features/* ]
    pull_request:
        branches: [ main ]

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Initial Message
              run: echo "Running tests for wimp"