name: Ubuntu Regression Tests

on:
    push:
        branches: [ main, develop, features/* ]
    pull_request:
        branches: [ main ]

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                submodules: recursive

            - name: Install dependencies
              run: sudo apt-get update && sudo apt-get install -y ninja-build

            - name: Configure build
              run: mkdir build && cd build && cmake .. -DCMAKE_CXX_COMPILER=gcc -DCMAKE_C_COMPILER=gcc -G "Ninja" -DWIMP_BUILD_TESTS=1

            - name: Build project
              run: cd build && cmake --build . -j10

            - name: List test executables
              run: ls build/bin/

            - name: install pip dependencies
              run: pip install -r tests/utility/wimp-test/requirements.txt

            - name: Run C test files through wimp-test.py and generate report
              run: cd ${{ github.workspace }} && python tests/utility/wimp-test/wimp-test.py --executable-root build/bin --report-file ubuntu_test_ctrf_report.json --compile-mode release --tests-root tests/configs/WIMP-C-Tests
            
            - name: Publish Summary Test Report
              uses: ctrf-io/github-test-reporter@v1
              with:
                report-path: 'ubuntu_test_ctrf_report.json'
                summary-report: true
              env:
                GITHUB_TOKEN: ${{ secrets.PR_TOKEN }}  
              if: always()

            - name: Publish Test List Report
              uses: ctrf-io/github-test-reporter@v1
              with:
                report-path: 'ubuntu_test_ctrf_report.json'
                test-list-report: true
              env:
                GITHUB_TOKEN: ${{ secrets.PR_TOKEN }}  
              if: always()            