name: Run Tests

on:
    push:
        branches: [ main, develop, features/* ]
    pull_request:
        branches: [ main ]

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                submodules: recursive

            - name: Install dependencies
              run: sudo apt-get update && sudo apt-get install -y ninja-build

            - name: Configure build
              run: mkdir build && cd build && cmake .. -DCMAKE_CXX_COMPILER=gcc -G "Ninja" -DWIMP_BUILD_TESTS=1

            - name: Build project
              run: cd build && cmake --build . -j10

            - name: List test executables
              run: ls build/bin/

            - name: Run test executables
              run: for file in build/bin/*Test*; do if [ -x "$file" ] && [[ "$file" != *_b ]]; then echo "Running $file"; ./$file; fi; done

            