name: Run Ubuntu Tests

on:
    push:
        branches: [ main, develop, features/* ]
    pull_request:
        branches: [ main ]

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                submodules: recursive

            - name: Install dependencies
              run: sudo apt-get update && sudo apt-get install -y ninja-build gcovr

            - name: Configure build
              run: mkdir build && cd build && cmake .. -DCMAKE_CXX_COMPILER=gcc -DCMAKE_C_COMPILER=gcc -G "Ninja" -DCMAKE_C_FLAGS="--coverage -g -O0" -DCMAKE_CXX_FLAGS="--coverage -g -O0" -DWIMP_BUILD_TESTS=1

            - name: Build project
              run: cd build && cmake --build . -j10

            - name: Run test executables
              run: for file in build/bin/*Test*; do if [ -x "$file" ] && [[ "$file" != *_b ]]; then echo "Running $file"; ./$file; fi; done

            - name: Generate coverage report
              run: |
                cd build
                gcovr --root .. --verbose --filter '^../wimp/.*' --cobertura coverage.xml --gcov-ignore-parse-errors=negative_hits.warn

            - name: Upload to Codecov
              uses: codecov/codecov-action@v2
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                fail_ci_if_error: true
                functionalities: fix