name: Windows Regression Tests

on:
    push:
        branches: [ main, develop, features/* ]
    pull_request:
        branches: [ main ]

jobs:
    tests:
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                submodules: recursive

            # C tests
            - name: Configure build
              run: |
                mkdir build
                cd build
                cmake .. -G "Visual Studio 17 2022" -A x64 -DWIMP_BUILD_TESTS=1

            - name: Build project
              run: cd build && cmake --build . --config Release

            - name: install pip dependencies
              run: pip install -r tests/utility/wimp-test/requirements.txt

            - name: Run C test files through wimp-test.py and generate report
              shell: pwsh
              run: |
                  cd ${{ github.workspace }}
                  python tests/utility/wimp-test/wimp-test.py --executable-root build/bin/Release --report-file windows_c_test_ctrf_report.json --compile-mode release --tests-root tests/configs/WIMP-C-Tests
            
            - name: Publish Summary Test Report
              uses: ctrf-io/github-test-reporter@v1
              with:
                report-path: 'windows_c_test_ctrf_report.json'
                summary-report: true
              env:
                GITHUB_TOKEN: ${{ secrets.PR_TOKEN }}  
              if: always()

            - name: Publish Test List Report
              uses: ctrf-io/github-test-reporter@v1
              with:
                report-path: 'windows_c_test_ctrf_report.json'
                test-list-report: true
              env:
                GITHUB_TOKEN: ${{ secrets.PR_TOKEN }}  
              if: always()
            
            # C# tests
            - name: Setup NuGet
              uses: NuGet/setup-nuget@v1.2.0

            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v2

            - name: Restore NuGet Packages
              run: nuget restore external/CS/wimp-cs/wimp-cs.sln

            - name: Build Solution
              run: msbuild external/CS/wimp-cs/wimp-cs.sln /p:Configuration=Release

            # List the files in the output directory for debugging purposes
            - name: List output directory
              run: dir build/bin/Release

            - name: Run C# test files through wimp-test.py and generate report
              shell: pwsh
              run: |
                  cd ${{ github.workspace }}
                  python tests/utility/wimp-test/wimp-test.py --executable-root build/bin/Release --report-file windows_cs_test_ctrf_report.json --compile-mode release --tests-root external/CS/tests/configs/WIMP-CS-Tests

            - name: Publish Summary Test Report
              uses: ctrf-io/github-test-reporter@v1
              with:
                report-path: 'windows_cs_test_ctrf_report.json'
                summary-report: true
              env:
                GITHUB_TOKEN: ${{ secrets.PR_TOKEN }}  
              if: always()

            - name: Publish Test List Report
              uses: ctrf-io/github-test-reporter@v1
              with:
                report-path: 'windows_cs_test_ctrf_report.json'
                test-list-report: true
              env:
                GITHUB_TOKEN: ${{ secrets.PR_TOKEN }}  
              if: always()