name: Run Windows Tests

on:
    push:
        branches: [ main, develop, features/* ]
    pull_request:
        branches: [ main ]

jobs:
    tests:
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                submodules: recursive

            - name: Configure build
              run: |
                mkdir build
                cd build
                cmake .. -G "Visual Studio 18 2026" -A x64 -DWIMP_BUILD_TESTS=1

            - name: Build project
              run: cd build && cmake --build . --config Debug

            - name: List test executables
              run: dir build\bin\
              shell: cmd

            - name: Run test executables
              run: |
                Get-ChildItem build\bin\*Test* | Where-Object { $_.Name -notlike "*_b*" } | ForEach-Object { Write-Host "Running $($_.FullName)"; & $_.FullName }
              shell: pwsh

            