name: Windows coverage report for Codecov

on:
    push:
        branches: [ main, develop, features/* ]
    pull_request:
        branches: [ main ]

jobs:
    tests:
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                submodules: recursive

            - name: Setup OpenCppCoverage and add to PATh
              id: setup_opencppcoverage
              run: |
                choco install OpenCppCoverage -y
                echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH

            - name: Configure build
              run: |
                mkdir build
                cd build
                cmake .. -G "Visual Studio 17 2022" -A x64 -DWIMP_BUILD_TESTS=1

            - name: Build project
              run: cd build && cmake --build . --config Debug

            - name: List test executables
              run: dir build\bin\Debug
              shell: cmd

            - name: Run Regression and Generate Coverage Report
              shell: pwsh
              run: |
                $testFiles = Get-ChildItem build\bin\Debug\*Test*.exe | Where-Object { $_.Name -notlike "*_b*" }
                foreach ($test in $testFiles) {
                  Write-Host "Running $($test.FullName) with coverage"
                  $outputFile = "$($test.BaseName)_coverage.xml"
                  echo "Output file: $outputFile"
                  & "OpenCppCoverage.exe" --sources wimp --excluded_sources "*utility*" --excluded_sources "*tests*" --modules wimp --excluded_modules plibsys --excluded_modules Test --excluded_modules "*tests*" --export_type "cobertura:$outputFile" -- "$($test.FullName)"
                }

            - name: Upload Report to Codecov
              uses: codecov/codecov-action@v2
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                fail_ci_if_error: true
                functionalities: fix