name: Run Windows Tests

on:
    push:
        branches: [ main, develop, features/* ]
    pull_request:
        branches: [ main ]

jobs:
    tests:
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                submodules: recursive

            - name: Install dependencies
              run: choco install opencppcoverage ninja --yes

            - name: Configure build
              run: |
                mkdir build
                cd build
                cmake .. -G "Ninja" -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl -DWIMP_BUILD_TESTS=1

            - name: Build project
              run: cd build && cmake --build . -j10

            - name: Run tests with coverage
              run: |
                $testFiles = Get-ChildItem build\bin\*Test* | Where-Object { $_.Name -notlike "*_b*" -and $_.Extension -ne ".pdb" -and $_.Extension -eq ".exe" }
                foreach ($test in $testFiles) {
                  Write-Host "Running $($test.FullName) with coverage"
                  & "C:\Program Files\OpenCppCoverage\OpenCppCoverage.exe" --sources wimp --export_type html:coverage_$($test.BaseName) -- $test.FullName
                }
              shell: pwsh

            - name: Upload coverage reports
              uses: actions/upload-artifact@v3
              with:
                name: coverage-reports
                path: coverage_*/